#!/bin/bash
# ===============================================================
# Matrix Morpheus GRUB Theme Installer (Universal)
# Supports multiple Linux distros: Arch, Debian, Ubuntu, and custom
# ===============================================================

set -e

THEME_NAME="Matrix"
THEME_DIR="/boot/grub/themes"
GRUB_CFG="/etc/default/grub"
GRUB_FILE="/boot/grub/grub.cfg"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ICONS_SRC="${SCRIPT_DIR}/${THEME_NAME}/icons"
ASSETS_DIR="${SCRIPT_DIR}/assets"
DISTROS_CONF="${SCRIPT_DIR}/distros.conf"

echo ""
echo "================================"
echo "Matrix Morpheus GRUB Theme Installer"
echo "================================"
echo ""

# Check for root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root (use sudo)."
    exit 1
fi

# Get distro identifier from system (substring match)
get_system_distro_id() {
    local id=""
    if [ -f /etc/os-release ]; then
        id=$(grep -E "^ID=|^NAME=" /etc/os-release | head -2 | cut -d= -f2 | tr -d '"' | tr '\n' ' ')
    fi
    # GRUB_DISTRIBUTOR is often `lsb_release -i -s` - get actual value
    local grub_dist
    grub_dist=$(lsb_release -i -s 2>/dev/null || true)
    [ -z "$grub_dist" ] && grub_dist="Debian"
    id="${id} ${grub_dist}"
    echo "$id" | tr 'A-Z' 'a-z'
}

# Find best matching distro from config (by priority, substring match)
find_distro_match() {
    local search_id="$1"
    while IFS='|' read -r keyword icon_on icon_off; do
        [[ "$keyword" =~ ^#.*$ ]] && continue
        [[ -z "$keyword" ]] && continue
        if [[ "$search_id" == *"$keyword"* ]]; then
            if [[ -f "${ICONS_SRC}/${icon_on}" && -f "${ICONS_SRC}/${icon_off}" ]]; then
                echo "${keyword}|${icon_on}|${icon_off}"
                return 0
            fi
        fi
    done < "$DISTROS_CONF"
    return 1
}

# List available distros for manual selection; prints list, distros in DISTROS_ARR
list_available_distros() {
    DISTROS_ARR=()
    local i=1
    while IFS='|' read -r keyword icon_on icon_off; do
        [[ "$keyword" =~ ^#.*$ ]] && continue
        [[ -z "$keyword" ]] && continue
        if [[ -f "${ICONS_SRC}/${icon_on}" && -f "${ICONS_SRC}/${icon_off}" ]]; then
            DISTROS_ARR+=("$keyword")
            echo "  $i) $keyword"
            ((i++))
        fi
    done < "$DISTROS_CONF"
}

# Get Linux class from grub.cfg (distro-specific class from first Linux menuentry)
get_linux_class_from_grub() {
    local grub_file="${1:-/tmp/grub_matrix_check.cfg}"
    if [ ! -f "$grub_file" ]; then
        grub-mkconfig 2>/dev/null > "$grub_file" || true
    fi
    # GRUB uses: --class debian --class gnu-linux ... ; we want the distro (debian/arch/ubuntu)
    local line
    line=$(grep -E "menuentry.*--class.*gnu-linux" "$grub_file" 2>/dev/null | head -1)
    for cls in $(echo "$line" | grep -oE '\-\-class [a-z0-9_-]+' | awk '{print $2}'); do
        case "$cls" in gnu-linux|gnu|os) ;; *) echo "$cls"; return ;; esac
    done
}

# Check if grub has Windows entry
has_windows_entry() {
    local grub_file="${1:-/tmp/grub_matrix_check.cfg}"
    grep -iE "menuentry.*[Ww]indows" "$grub_file" 2>/dev/null | head -1 | grep -q .
}

# Count top-level menuentries (at start of line, excluding those inside submenus)
count_menu_entries() {
    local grub_file="${1:-/tmp/grub_matrix_check.cfg}"
    grep -c "^menuentry " "$grub_file" 2>/dev/null || echo "0"
}

# Generate placeholder grub.d script
create_placeholder_script() {
    cat << 'SCRIPT_END'
#!/bin/sh
# Matrix theme placeholder - ensures two-entry layout when only one OS exists
# Generated by Matrix Morpheus GRUB Theme installer

echo "menuentry 'Linux (Matrix placeholder)' --class linux --class gnu-linux --class gnu --class os { true }"
SCRIPT_END
}

echo "Detecting system configuration..."
# Preview grub config
grub-mkconfig 2>/dev/null > /tmp/grub_matrix_check.cfg || true

# Ask user: auto-detect or manual
echo ""
echo "How do you want to select the Linux distribution for icons?"
echo "  1) Auto-detect (recommended)"
echo "  2) Select manually"
echo -n "Enter choice [1]: "
read -r choice
choice="${choice:-1}"

SELECTED_DISTRO=""
SELECTED_ICON_ON=""
SELECTED_ICON_OFF=""
LINUX_CLASS=""

if [ "$choice" = "2" ]; then
    # Manual selection
    echo ""
    echo "Available distributions (with icons in Matrix/icons/):"
    list_available_distros
    echo ""
    echo -n "Enter number: "
    read -r num
    if [[ "$num" =~ ^[0-9]+$ ]] && [ "$num" -ge 1 ] && [ "$num" -le "${#DISTROS_ARR[@]}" ]; then
        SELECTED_DISTRO="${DISTROS_ARR[$((num-1))]}"
        while IFS='|' read -r kw io iof; do
            [[ "$kw" == "$SELECTED_DISTRO" ]] && SELECTED_ICON_ON="$io" && SELECTED_ICON_OFF="$iof" && break
        done < "$DISTROS_CONF"
        LINUX_CLASS="$SELECTED_DISTRO"
    else
        echo "Invalid choice. Using auto-detect."
        choice="1"
    fi
fi

if [ "$choice" = "1" ] || [ -z "$SELECTED_DISTRO" ]; then
    # Auto-detect
    system_id=$(get_system_distro_id)
    match=$(find_distro_match "$system_id")
    if [ -n "$match" ]; then
        SELECTED_DISTRO=$(echo "$match" | cut -d'|' -f1)
        SELECTED_ICON_ON=$(echo "$match" | cut -d'|' -f2)
        SELECTED_ICON_OFF=$(echo "$match" | cut -d'|' -f3)
        LINUX_CLASS=$(get_linux_class_from_grub /tmp/grub_matrix_check.cfg)
        LINUX_CLASS="${LINUX_CLASS:-$SELECTED_DISTRO}"
        echo "Detected: $SELECTED_DISTRO (using icons: $SELECTED_ICON_ON / $SELECTED_ICON_OFF)"
    else
        echo "No matching distro found. Using linux_template.png as fallback."
        LINUX_CLASS=$(get_linux_class_from_grub /tmp/grub_matrix_check.cfg)
        LINUX_CLASS="${LINUX_CLASS:-gnu-linux}"
    fi
fi

# Ensure theme directory exists
echo ""
echo "Installing theme..."
mkdir -p "$THEME_DIR"

# Copy theme (excluding icons - we'll set them up)
rm -rf "${THEME_DIR}/${THEME_NAME}"
cp -r "$THEME_NAME" "$THEME_DIR/"
ICONS_DST="${THEME_DIR}/${THEME_NAME}/icons"
mkdir -p "$ICONS_DST"

# Prepare Linux icon
if [ -n "$SELECTED_ICON_ON" ] && [ -f "${ICONS_SRC}/${SELECTED_ICON_ON}" ]; then
    cp "${ICONS_SRC}/${SELECTED_ICON_ON}" "${ICONS_DST}/${LINUX_CLASS}.png"
    echo "  Linux icon: ${LINUX_CLASS}.png (from $SELECTED_ICON_ON)"
else
    # Fallback to template
    if [ -f "${ASSETS_DIR}/linux_template.png" ]; then
        cp "${ASSETS_DIR}/linux_template.png" "${ICONS_DST}/${LINUX_CLASS}.png"
        cp "${ASSETS_DIR}/linux_template.png" "${ICONS_DST}/gnu-linux.png"
        echo "  Linux icon: ${LINUX_CLASS}.png (fallback: linux_template.png)"
    fi
fi

# Prepare Windows icon
if [ -f "${ASSETS_DIR}/windows_template.png" ]; then
    cp "${ASSETS_DIR}/windows_template.png" "${ICONS_DST}/windows.png"
    echo "  Windows icon: windows.png (from windows_template.png)"
elif [ -f "${ICONS_SRC}/windows_on.png" ]; then
    cp "${ICONS_SRC}/windows_on.png" "${ICONS_DST}/windows.png"
else
    # Copy all icons from source (may have windows)
    for f in "${ICONS_SRC}"/*.png; do
        [ -f "$f" ] && cp "$f" "$ICONS_DST/"
    done
fi

# Ensure we have gnu-linux fallback
if [ ! -f "${ICONS_DST}/gnu-linux.png" ] && [ -f "${ICONS_DST}/${LINUX_CLASS}.png" ]; then
    cp "${ICONS_DST}/${LINUX_CLASS}.png" "${ICONS_DST}/gnu-linux.png"
fi

# Add placeholder if only one entry (Windows only or no entries)
ENTRY_COUNT=$(count_menu_entries /tmp/grub_matrix_check.cfg)

if [ "$ENTRY_COUNT" -le 1 ]; then
    echo ""
    echo "Adding placeholder entry for two-option layout..."
    create_placeholder_script > /etc/grub.d/06_matrix_placeholder
    chmod +x /etc/grub.d/06_matrix_placeholder
    # Ensure linux placeholder icon exists
    if [ ! -f "${ICONS_DST}/linux.png" ] && [ -f "${ASSETS_DIR}/linux_template.png" ]; then
        cp "${ASSETS_DIR}/linux_template.png" "${ICONS_DST}/linux.png"
    fi
else
    # Remove placeholder script if we have enough entries
    rm -f /etc/grub.d/06_matrix_placeholder
fi

# Configure GRUB to use the theme
echo ""
echo "Updating GRUB configuration..."
if grep -q '^GRUB_THEME=' "$GRUB_CFG"; then
    sed -i "s|^GRUB_THEME=.*|GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\"|" "$GRUB_CFG"
else
    echo "" >> "$GRUB_CFG"
    echo "GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\"" >> "$GRUB_CFG"
fi

# Regenerate GRUB
echo "Rebuilding GRUB configuration..."
if command -v grub-mkconfig >/dev/null 2>&1; then
    grub-mkconfig -o "$GRUB_FILE" >/dev/null
    echo "GRUB configuration updated successfully."
else
    echo "grub-mkconfig not found. Please update your GRUB manually."
    exit 1
fi

# Cleanup
rm -f /tmp/grub_matrix_check.cfg

echo ""
echo "Installation complete!"
echo "Reboot to see your new Matrix Morpheus theme."
echo ""
