#!/bin/bash
# ===============================================================
# Matrix Morpheus GRUB Theme Installer (Universal)
# Supports multiple Linux distros: Arch, Debian, Ubuntu, and custom
# ===============================================================

set -e

THEME_NAME="Matrix"
THEME_DIR="/boot/grub/themes"
GRUB_CFG="/etc/default/grub"
GRUB_FILE="/boot/grub/grub.cfg"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ICONS_SRC="${SCRIPT_DIR}/${THEME_NAME}/icons"
ASSETS_DIR="${SCRIPT_DIR}/assets"
DISTROS_CONF="${SCRIPT_DIR}/distros.conf"
GRUB_CHECK_CFG="/tmp/grub_matrix_check.cfg"

echo ""
echo "================================"
echo "Matrix Morpheus GRUB Theme Installer"
echo "================================"
echo ""

# Check for root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root (use sudo)."
    exit 1
fi

# Get distro identifier from system (substring match)
get_system_distro_id() {
    local id=""
    if [ -f /etc/os-release ]; then
        id=$(grep -E "^ID=|^NAME=" /etc/os-release | head -2 | cut -d= -f2 | tr -d '"' | tr '\n' ' ')
    fi
    local grub_dist
    grub_dist=$(lsb_release -i -s 2>/dev/null || true)
    [ -z "$grub_dist" ] && grub_dist="Debian"
    id="${id} ${grub_dist}"
    echo "$id" | tr 'A-Z' 'a-z'
}

# Find best matching distro from config (by priority, substring match)
find_distro_match() {
    local search_id="$1"
    while IFS='|' read -r keyword icon_on icon_off; do
        [[ "$keyword" =~ ^#.*$ ]] && continue
        [[ -z "$keyword" ]] && continue
        if [[ "$search_id" == *"$keyword"* ]]; then
            if [[ -f "${ICONS_SRC}/${icon_on}" && -f "${ICONS_SRC}/${icon_off}" ]]; then
                echo "${keyword}|${icon_on}|${icon_off}"
                return 0
            fi
        fi
    done < "$DISTROS_CONF"
    return 1
}

# List available distros for manual selection; prints list, distros in DISTROS_ARR
list_available_distros() {
    DISTROS_ARR=()
    local i=1
    while IFS='|' read -r keyword icon_on icon_off; do
        [[ "$keyword" =~ ^#.*$ ]] && continue
        [[ -z "$keyword" ]] && continue
        if [[ -f "${ICONS_SRC}/${icon_on}" && -f "${ICONS_SRC}/${icon_off}" ]]; then
            DISTROS_ARR+=("$keyword")
            echo "  $i) $keyword"
            i=$((i+1))
        fi
    done < "$DISTROS_CONF"
}

# Count top-level menuentries (no leading space = top-level, not inside submenu)
count_menu_entries() {
    local grub_file="${1:-$GRUB_CHECK_CFG}"
    grep -c "^menuentry " "$grub_file" 2>/dev/null || echo "0"
}

# Parse menu entries into ENTRY_TITLES and ENTRY_CLASSES arrays (1-indexed)
parse_menu_entries() {
    local grub_file="${1:-$GRUB_CHECK_CFG}"
    ENTRY_TITLES=()
    ENTRY_CLASSES=()
    local idx=0
    while IFS= read -r line; do
        local title
        title=$(echo "$line" | sed -n "s/.*menuentry[[:space:]]*'\([^']*\)'.*/\1/p")
        local classes
        classes=$(echo "$line" | grep -oE '\-\-class[[:space:]]+[a-z0-9_-]+' | awk '{print $2}' | tr '\n' ' ')
        ENTRY_TITLES[idx]="$title"
        ENTRY_CLASSES[idx]="$classes"
        idx=$((idx+1))
    done < <(grep "^menuentry " "$grub_file" 2>/dev/null | head -10)
}

# Check if entry looks like Linux (has gnu-linux or distro class)
entry_is_linux() {
    local classes="$1"
    local title="$2"
    [[ "$classes" == *"gnu-linux"* ]] && return 0
    [[ "$classes" == *"debian"* ]] && return 0
    [[ "$classes" == *"arch"* ]] && return 0
    [[ "$classes" == *"ubuntu"* ]] && return 0
    [[ "$classes" == *"linux"* ]] && return 0
    [[ "$title" =~ [Ll]inux ]] && return 0
    [[ "$title" =~ [Dd]ebian ]] && return 0
    [[ "$title" =~ [Uu]buntu ]] && return 0
    [[ "$title" =~ [Aa]rch ]] && return 0
    return 1
}

# Check if entry looks like Windows
entry_is_windows() {
    local classes="$1"
    local title="$2"
    [[ "$classes" == *"windows"* ]] && return 0
    [[ "$classes" == *"win"* ]] && return 0
    [[ "$title" =~ [Ww]indows ]] && return 0
    return 1
}

# Get first usable class for icon (skip gnu, os)
get_primary_class() {
    local classes="$1"
    for cls in $classes; do
        case "$cls" in
            gnu|os) ;;
            *) echo "$cls"; return ;;
        esac
    done
}

# Generate placeholder grub.d script
create_placeholder_script() {
    cat << 'SCRIPT_END'
#!/bin/sh
# Matrix theme placeholder - ensures two-entry layout when only one OS exists
# Generated by Matrix Morpheus GRUB Theme installer

echo "menuentry 'Linux (Matrix placeholder)' --class linux --class gnu-linux --class gnu --class os { true }"
SCRIPT_END
}

# Apply resolution to theme.txt (scale icons for 2K/4K)
apply_resolution_to_theme() {
    local res="$1"
    local theme_file="$2"
    local iw ih
    case "$res" in
        1280x720)  iw=1280;  ih=720  ;;
        1920x1080) iw=1920;  ih=1080 ;;
        2560x1440) iw=2560;  ih=1440 ;;
        3840x2160) iw=3840;  ih=2160 ;;
        *) return ;;  # auto - use default
    esac
    sed -i "s/icon_width = [0-9]*/icon_width = $iw/" "$theme_file"
    sed -i "s/icon_height = [0-9]*/icon_height = $ih/" "$theme_file"
    sed -i "s/item_height = [0-9]*/item_height = $ih/" "$theme_file"
}

echo "Detecting system configuration..."
grub-mkconfig 2>/dev/null > "$GRUB_CHECK_CFG" || true

ENTRY_COUNT=$(count_menu_entries "$GRUB_CHECK_CFG")

# Check: theme is designed for exactly 2 choices
if [ "$ENTRY_COUNT" -gt 2 ]; then
    echo ""
    echo "----------------------------------------"
    echo "  This theme supports only 2 boot entries"
    echo "----------------------------------------"
    echo ""
    echo "You currently have $ENTRY_COUNT menu entries (e.g. multiple distros,"
    echo "UEFI Firmware Settings, Advanced options, etc.)."
    echo ""
    echo "This Matrix theme is designed for choosing between exactly TWO options:"
    echo "  - Your Linux distribution"
    echo "  - Windows"
    echo ""
    echo "Please reduce your GRUB menu to 2 entries by editing:"
    echo "  - /etc/default/grub (e.g. GRUB_DISABLE_OS_PROBER, GRUB_DISABLE_RECOVERY)"
    echo "  - Scripts in /etc/grub.d/ (disable or remove unwanted entries)"
    echo ""
    echo "Then run: sudo update-grub  (or grub-mkconfig -o /boot/grub/grub.cfg)"
    echo "After that, run this installer again."
    echo ""
    rm -f "$GRUB_CHECK_CFG"
    exit 1
fi

# Screen resolution
echo ""
echo "Select your display resolution for GRUB (fixes small/big loader):"
echo "  1) HD        (1280x720)"
echo "  2) Full HD   (1920x1080)"
echo "  3) 2K        (2560x1440)"
echo "  4) 4K        (3840x2160)"
echo -n "Enter choice [2]: "
read -r res_choice
res_choice="${res_choice:-2}"

case "$res_choice" in
    1) GRUB_GFXMODE="1280x720x24,auto"  ; RES_FOR_THEME="1280x720"  ;;
    2) GRUB_GFXMODE="1920x1080x24,auto" ; RES_FOR_THEME="1920x1080" ;;
    3) GRUB_GFXMODE="2560x1440x24,1920x1080x24,auto" ; RES_FOR_THEME="2560x1440" ;;
    4) GRUB_GFXMODE="3840x2160x24,1920x1080x24,auto" ; RES_FOR_THEME="3840x2160" ;;
    *) GRUB_GFXMODE="1920x1080x24,auto" ; RES_FOR_THEME="1920x1080" ;;
esac

# Identify Linux and Windows entries (when we have 2)
LINUX_ENTRY_NUM=""
WINDOWS_ENTRY_NUM=""
LINUX_ENTRY_CLASS=""
WINDOWS_ENTRY_CLASS=""

if [ "$ENTRY_COUNT" -eq 2 ]; then
    parse_menu_entries "$GRUB_CHECK_CFG"
    ENTRY1_TITLE="${ENTRY_TITLES[0]:-}"
    ENTRY1_CLASSES="${ENTRY_CLASSES[0]:-}"
    ENTRY2_TITLE="${ENTRY_TITLES[1]:-}"
    ENTRY2_CLASSES="${ENTRY_CLASSES[1]:-}"
    
    # Auto-detect
    if entry_is_linux "$ENTRY1_CLASSES" "$ENTRY1_TITLE" && entry_is_windows "$ENTRY2_CLASSES" "$ENTRY2_TITLE"; then
        LINUX_ENTRY_NUM=1
        WINDOWS_ENTRY_NUM=2
        LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
        WINDOWS_ENTRY_CLASS=$(get_primary_class "$ENTRY2_CLASSES")
        LINUX_ENTRY_CLASS="${LINUX_ENTRY_CLASS:-$LINUX_CLASS}"
        WINDOWS_ENTRY_CLASS="${WINDOWS_ENTRY_CLASS:-windows}"
        echo "Auto-detected: Entry 1 = Linux ($ENTRY1_TITLE), Entry 2 = Windows ($ENTRY2_TITLE)"
    elif entry_is_windows "$ENTRY1_CLASSES" "$ENTRY1_TITLE" && entry_is_linux "$ENTRY2_CLASSES" "$ENTRY2_TITLE"; then
        LINUX_ENTRY_NUM=2
        WINDOWS_ENTRY_NUM=1
        LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY2_CLASSES")
        WINDOWS_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
        LINUX_ENTRY_CLASS="${LINUX_ENTRY_CLASS:-$LINUX_CLASS}"
        WINDOWS_ENTRY_CLASS="${WINDOWS_ENTRY_CLASS:-windows}"
        echo "Auto-detected: Entry 1 = Windows ($ENTRY1_TITLE), Entry 2 = Linux ($ENTRY2_TITLE)"
    else
        # Ask user
        echo ""
        echo "Could not auto-detect which entry is Linux and which is Windows."
        echo ""
        echo "Menu entries:"
        echo "  1) $ENTRY1_TITLE"
        echo "  2) $ENTRY2_TITLE"
        echo ""
        echo -n "Which entry is Linux? Enter number [1]: "
        read -r linux_num
        linux_num="${linux_num:-1}"
        echo -n "Which entry is Windows? Enter number [2]: "
        read -r win_num
        win_num="${win_num:-2}"
        
        if [ "$linux_num" = "1" ] && [ "$win_num" = "2" ]; then
            LINUX_ENTRY_NUM=1
            WINDOWS_ENTRY_NUM=2
            LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
            WINDOWS_ENTRY_CLASS=$(get_primary_class "$ENTRY2_CLASSES")
        elif [ "$linux_num" = "2" ] && [ "$win_num" = "1" ]; then
            LINUX_ENTRY_NUM=2
            WINDOWS_ENTRY_NUM=1
            LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY2_CLASSES")
            WINDOWS_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
        else
            echo "Using defaults. Entry 1 = Linux, Entry 2 = Windows."
            LINUX_ENTRY_NUM=1
            WINDOWS_ENTRY_NUM=2
            LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
            WINDOWS_ENTRY_CLASS=$(get_primary_class "$ENTRY2_CLASSES")
        fi
        LINUX_ENTRY_CLASS="${LINUX_ENTRY_CLASS:-gnu-linux}"
        WINDOWS_ENTRY_CLASS="${WINDOWS_ENTRY_CLASS:-windows}"
    fi
elif [ "$ENTRY_COUNT" -eq 1 ]; then
    parse_menu_entries "$GRUB_CHECK_CFG"
    ENTRY1_TITLE="${ENTRY_TITLES[0]:-}"
    ENTRY1_CLASSES="${ENTRY_CLASSES[0]:-}"
    if entry_is_linux "$ENTRY1_CLASSES" "$ENTRY1_TITLE"; then
        LINUX_ENTRY_NUM=1
        LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
        LINUX_ENTRY_CLASS="${LINUX_ENTRY_CLASS:-gnu-linux}"
    elif entry_is_windows "$ENTRY1_CLASSES" "$ENTRY1_TITLE"; then
        WINDOWS_ENTRY_NUM=1
        WINDOWS_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
        WINDOWS_ENTRY_CLASS="${WINDOWS_ENTRY_CLASS:-windows}"
    else
        echo ""
        echo "Could not identify the single boot entry. Is it Linux or Windows?"
        echo "  1) $ENTRY1_TITLE"
        echo ""
        echo -n "Enter 1 for Linux, 2 for Windows [1]: "
        read -r ident
        ident="${ident:-1}"
        if [ "$ident" = "2" ]; then
            WINDOWS_ENTRY_NUM=1
            WINDOWS_ENTRY_CLASS="windows"
        else
            LINUX_ENTRY_NUM=1
            LINUX_ENTRY_CLASS=$(get_primary_class "$ENTRY1_CLASSES")
            LINUX_ENTRY_CLASS="${LINUX_ENTRY_CLASS:-gnu-linux}"
        fi
    fi
fi

# Find Linux distro for icons: auto-detect from entry class/title and system, ask only if not found
SELECTED_DISTRO=""
SELECTED_ICON_ON=""
SELECTED_ICON_OFF=""

if [ -n "$LINUX_ENTRY_NUM" ]; then
    # Search string: Linux entry class + title + system id
    if [ "$LINUX_ENTRY_NUM" = "1" ]; then
        search_str="${LINUX_ENTRY_CLASS:-} ${ENTRY1_TITLE:-} ${ENTRY1_CLASSES:-}"
    else
        search_str="${LINUX_ENTRY_CLASS:-} ${ENTRY2_TITLE:-} ${ENTRY2_CLASSES:-}"
    fi
    search_str="${search_str} $(get_system_distro_id)"
    search_str=$(echo "$search_str" | tr 'A-Z' 'a-z')

    match=$(find_distro_match "$search_str")
    if [ -n "$match" ]; then
        SELECTED_DISTRO=$(echo "$match" | cut -d'|' -f1)
        SELECTED_ICON_ON=$(echo "$match" | cut -d'|' -f2)
        SELECTED_ICON_OFF=$(echo "$match" | cut -d'|' -f3)
        echo "Found Linux: $SELECTED_DISTRO"
    else
        echo ""
        echo "Could not identify the Linux distribution. Please select which icons to use:"
        list_available_distros
        echo ""
        echo -n "Enter number: "
        read -r num
        if [[ "$num" =~ ^[0-9]+$ ]] && [ "$num" -ge 1 ] && [ "$num" -le "${#DISTROS_ARR[@]}" ]; then
            SELECTED_DISTRO="${DISTROS_ARR[$((num-1))]}"
            while IFS='|' read -r kw io iof; do
                [[ "$kw" == "$SELECTED_DISTRO" ]] && SELECTED_ICON_ON="$io" && SELECTED_ICON_OFF="$iof" && break
            done < "$DISTROS_CONF"
        else
            echo "Using linux_template.png as fallback."
        fi
    fi
fi

# Install theme
echo ""
echo "Installing theme..."
mkdir -p "$THEME_DIR"
rm -rf "${THEME_DIR}/${THEME_NAME}"
cp -r "$THEME_NAME" "$THEME_DIR/"
ICONS_DST="${THEME_DIR}/${THEME_NAME}/icons"
mkdir -p "$ICONS_DST"

# Apply resolution to theme if needed
if [ -n "$RES_FOR_THEME" ]; then
    apply_resolution_to_theme "$RES_FOR_THEME" "${THEME_DIR}/${THEME_NAME}/theme.txt"
fi

# Prepare Linux icon(s)
LINUX_ICON_CLASS="${LINUX_ENTRY_CLASS:-$LINUX_CLASS}"
if [ -n "$SELECTED_ICON_ON" ] && [ -f "${ICONS_SRC}/${SELECTED_ICON_ON}" ]; then
    cp "${ICONS_SRC}/${SELECTED_ICON_ON}" "${ICONS_DST}/${LINUX_ICON_CLASS}.png"
    echo "  Linux icon: ${LINUX_ICON_CLASS}.png (from $SELECTED_ICON_ON)"
else
    if [ -f "${ASSETS_DIR}/linux_template.png" ]; then
        cp "${ASSETS_DIR}/linux_template.png" "${ICONS_DST}/${LINUX_ICON_CLASS}.png"
        cp "${ASSETS_DIR}/linux_template.png" "${ICONS_DST}/gnu-linux.png"
        echo "  Linux icon: ${LINUX_ICON_CLASS}.png (fallback: linux_template.png)"
    fi
fi

# Prepare Windows icon: use _off from same distro (opposite pill), fallback to template
if [ -n "$WINDOWS_ENTRY_CLASS" ]; then
    if [ -n "$SELECTED_ICON_OFF" ] && [ -f "${ICONS_SRC}/${SELECTED_ICON_OFF}" ]; then
        cp "${ICONS_SRC}/${SELECTED_ICON_OFF}" "${ICONS_DST}/${WINDOWS_ENTRY_CLASS}.png"
        echo "  Windows icon: ${WINDOWS_ENTRY_CLASS}.png (from $SELECTED_ICON_OFF)"
    elif [ -f "${ASSETS_DIR}/windows_template.png" ]; then
        cp "${ASSETS_DIR}/windows_template.png" "${ICONS_DST}/${WINDOWS_ENTRY_CLASS}.png"
        echo "  Windows icon: ${WINDOWS_ENTRY_CLASS}.png (from windows_template.png)"
    fi
fi
if [ ! -f "${ICONS_DST}/windows.png" ]; then
    if [ -n "$SELECTED_ICON_OFF" ] && [ -f "${ICONS_SRC}/${SELECTED_ICON_OFF}" ]; then
        cp "${ICONS_SRC}/${SELECTED_ICON_OFF}" "${ICONS_DST}/windows.png"
        echo "  Windows icon: windows.png (from $SELECTED_ICON_OFF)"
    elif [ -f "${ASSETS_DIR}/windows_template.png" ]; then
        cp "${ASSETS_DIR}/windows_template.png" "${ICONS_DST}/windows.png"
    elif [ -f "${ICONS_SRC}/windows_on.png" ]; then
        cp "${ICONS_SRC}/windows_on.png" "${ICONS_DST}/windows.png"
    fi
fi

# Ensure gnu-linux fallback
if [ ! -f "${ICONS_DST}/gnu-linux.png" ] && [ -f "${ICONS_DST}/${LINUX_ICON_CLASS}.png" ]; then
    cp "${ICONS_DST}/${LINUX_ICON_CLASS}.png" "${ICONS_DST}/gnu-linux.png"
fi

# Hide "Loading Linux..." and blue Debian background during boot
BLACK_PNG="${THEME_DIR}/${THEME_NAME}/black.png"
if [ -f "${ASSETS_DIR}/black.png" ]; then
    cp "${ASSETS_DIR}/black.png" "$BLACK_PNG"
fi
if [ -f "$BLACK_PNG" ]; then
    if grep -q '^GRUB_BACKGROUND=' "$GRUB_CFG"; then
        sed -i "s|^GRUB_BACKGROUND=.*|GRUB_BACKGROUND=\"${BLACK_PNG}\"|" "$GRUB_CFG"
    else
        echo "GRUB_BACKGROUND=\"${BLACK_PNG}\"" >> "$GRUB_CFG"
    fi
    echo "  Boot transition: black background (hides Debian blue)"
fi
for linux_script in /etc/grub.d/proxifiedScripts/linux /etc/grub.d/10_linux; do
    if [ -f "$linux_script" ] && grep -q 'quiet_boot="0"' "$linux_script" 2>/dev/null; then
        sed -i 's/quiet_boot="0"/quiet_boot="1"/' "$linux_script"
        echo "  Boot transition: quiet mode (hides Loading... messages)"
        break
    fi
done 2>/dev/null || true

# Placeholder for 1 or 0 entries
if [ "$ENTRY_COUNT" -le 1 ]; then
    echo ""
    echo "Adding placeholder entry for two-option layout..."
    create_placeholder_script > /etc/grub.d/06_matrix_placeholder
    chmod +x /etc/grub.d/06_matrix_placeholder
    if [ ! -f "${ICONS_DST}/linux.png" ] && [ -f "${ASSETS_DIR}/linux_template.png" ]; then
        cp "${ASSETS_DIR}/linux_template.png" "${ICONS_DST}/linux.png"
    fi
else
    rm -f /etc/grub.d/06_matrix_placeholder
fi

# Configure GRUB
echo ""
echo "Updating GRUB configuration..."
if grep -q '^GRUB_THEME=' "$GRUB_CFG"; then
    sed -i "s|^GRUB_THEME=.*|GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\"|" "$GRUB_CFG"
else
    echo "" >> "$GRUB_CFG"
    echo "GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\"" >> "$GRUB_CFG"
fi

# Set GRUB_GFXMODE
if grep -q '^GRUB_GFXMODE=' "$GRUB_CFG"; then
    sed -i "s|^GRUB_GFXMODE=.*|GRUB_GFXMODE=\"${GRUB_GFXMODE}\"|" "$GRUB_CFG"
else
    echo "GRUB_GFXMODE=\"${GRUB_GFXMODE}\"" >> "$GRUB_CFG"
fi
if ! grep -q '^GRUB_GFXPAYLOAD_LINUX=' "$GRUB_CFG"; then
    echo "GRUB_GFXPAYLOAD_LINUX=keep" >> "$GRUB_CFG"
fi

# Regenerate GRUB
echo "Rebuilding GRUB configuration..."
if command -v grub-mkconfig >/dev/null 2>&1; then
    grub-mkconfig -o "$GRUB_FILE" >/dev/null
    echo "GRUB configuration updated successfully."
else
    echo "grub-mkconfig not found. Please update your GRUB manually."
    exit 1
fi

rm -f "$GRUB_CHECK_CFG"

echo ""
echo "Installation complete!"
echo "Reboot to see your new Matrix Morpheus theme."
echo ""
